name: Dev Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Docker 
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ${{ secrets.pttgcdevopsarc09.azurecr.io }}/user-service:${{ github.sha }} .
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.pttgcdevopsarc09.azurecr.io }}
          username: ${{ secrets.admin }}
          password: ${{ secrets. lf5PlFHgS3D }}
      - run: docker push ${{ secrets.pttgcdevopsarc09.azurecr.io }}/user-service:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy via argoCD
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "zeabix-cloud-native/pttgc-devops-lab10-cd"  ## Change this to your CD repository
          ref: 'main'
          token: ${{ secrets.CD_PAT }}
      - name: Update image version
        run: yq -i e '.userService.tag="${{ github.sha }}"' values.yaml
        working-directory: ./production
      - name: Commit & Push changes
        run: |
          git config --global user.email 'DevOps'
          git config --global user.name  'devops@zeabix.com'
          git add .
          git commit -m "CD deployment with tag ${{ github.sha }}"
          git push https://${{ secrets.CD_PAT }}@github.com/zeabix-cloud-native/pttgc-devops-lab10-cd.git
